
universe = vanilla

executable = /home/home1/institut_3a/tacke/Bachelor_thesis/dt_scint_analysis_tools/scripts/ba_scripts/condor_submit/condor_exec.sh

arguments = $(ExecutableFile) $(dataset_name)

stdout = stdout/stdout-ClusterId$(ClusterId)-ProcId$(ProcId).ansi
stderr = stderr/stderr-ClusterId$(ClusterId)-ProcId$(ProcId).err
log = condorlog/condorlog-ClusterId$(ClusterId).log
stream_output = true
stream_error = true
request_cpus = 1
request_memory = 5G
request_disk = 500M

should_transfer_files = yes
when_to_transfer_output = on_exit

queue ExecutableFile, dataset_name from condor_joblist.csv

